env:
  node: true
  browser: true
  commonjs: true
  es6: true
extends:
  - eslint:recommended
  - plugin:react/recommended
parserOptions:
  sourceType: module
  scmaVersion: 7
  ecmaFeatures:
    jsx: true
plugins:
  - react
rules:
  indent:
    - error
    - 2
  react/jsx-uses-react:
    - error
  react/jsx-uses-vars:
    - error
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-extra-semi:
    - error
